#!/usr/bin/env bash

local branch

git fetch --all --tags --prune
branch="$(git-select-branch $1)"

if [[ -n "${branch}" ]]; then
  git checkout master

  if [[ $(git remote show | rg upstream) ]]; then
    git pull upstream master
    git push origin master
  else
    git pull
  fi

  git-push-delete-origin "${branch}"
  git branch --delete --force "${branch}"

  git-fresh -f
fi
