#!/usr/bin/env bash

if [[ "$1" == "1.9" ]]; then
  url="https://v1-9.docs.kubernetes.io/docs/api-reference/v1.9/"
else
  url="https://kubernetes.io/docs/reference/generated/kubernetes-api/v$1/"
fi

open ${url}
