#!/usr/bin/env bash

unset KUBECONFIG
kubeconfig="${HOME}/.kube/config"

if [[ -f "${kubeconfig}" ]];then
  echo "Kubeconfig is a file!"
  return 1
fi

mkdir -p "${kubeconfig}"

for f in ${kubeconfig}/*.yaml; do
  [[ -f "$f" ]] && KUBECONFIG="$f:${KUBECONFIG}"
done

export KUBECONFIG
