#!/usr/bin/env bash

local rancher_tmp=$(mktemp)
local kube_tmp=$(mktemp)

for cluster_id in $(curl -k -s -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" https://rke.mlbinfra.net/v3/clusters \
  | jq -r '.data[].id'); do

  curl -k -s -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" -X POST -H 'Accept: application/json'  -d '{}' \
    -H 'Content-Type: application/json' \
    "https://rke.mlbinfra.net/v3/clusters/${cluster_id}?action=generateKubeconfig" | jq -r '.config' > ${rancher_tmp}

  KUBECONFIG=${HOME}/.kube/config:${rancher_tmp} kubectl config view --merge --flatten > ${kube_tmp}
  cp ${kube_tmp} ${HOME}/.kube/config
done
