alias ga "git add"
alias gaa "git add --all"
alias gb "git branch"
alias gba "git branch -a"
alias gbr "git branch --remote"
alias gc "git commit -v"
alias gc! "git commit --amend -v"
alias gca "git commit -a -v"
alias gca! "git commit -a --amend -v"
alias gcm "git checkout master"
alias gco "git checkout"
alias gd "git diff"
alias gfa "git fetch --all --prune"
alias gl "git pull"
alias glog "git log --color --decorate --graph --oneline"
alias gm "git merge"
alias gp "git push"
alias gr "git remote"
alias grba "git rebase --abort"
alias grbc "git rebase --continue"
alias grbi "git rebase -i"
alias grh "git reset HEAD"
alias grhh "git reset HEAD --hard"
alias grmv "git remote rename"
alias grrm "git remote remove"
alias grset "git remote set-url"
alias grup "git remote update"
alias gst "git status"
alias gsta "git stash"
alias gstp "git stash pop"

set -x GOPATH ~/dev/golang
set -x PATH $PATH $GOPATH/bin
